version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: dtct_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: datacenter
      POSTGRES_USER: datacenter
      POSTGRES_PASSWORD: datacenter
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U datacenter -d datacenter']
      interval: 30s
      timeout: 10s
      retries: 3
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: datacenter-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie.develop
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_dev_data:
    driver: local